# Generated by Django 5.2.2 on 2025-09-13 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_register',
            fields=[
                ('Ast_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Ast_Type', models.CharField(max_length=3)),
                ('Ast_Brand', models.CharField(max_length=15)),
                ('Ast_Model', models.CharField(max_length=15)),
                ('Ast_Isrent', models.BooleanField(default=True)),
                ('Ast_Price', models.IntegerField()),
                ('Ast_document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_listing',
            fields=[
                ('Plate_no', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Vehicle_type', models.CharField(max_length=10)),
                ('Engine_type', models.CharField(max_length=6)),
                ('Fuel_type', models.CharField(max_length=8)),
                ('color', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('mileage', models.IntegerField()),
                ('Purchase', models.IntegerField()),
                ('Insurance', models.CharField(max_length=25)),
                ('chasis_no', models.CharField(max_length=30)),
                ('Engine_no', models.CharField(max_length=50)),
                ('Rent', models.IntegerField()),
                ('meter_In', models.IntegerField()),
                ('Ast_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset_register')),
            ],
        ),
        migrations.CreateModel(
            name='maintaince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(max_length=20)),
                ('Expense', models.IntegerField()),
                ('Description', models.TextField()),
                ('Document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('vehicle_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.vehicle_listing')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.vehicle_listing')),
            ],
        ),
    ]
