# Generated by Django 5.2.2 on 2025-09-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_register',
            name='addedby',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
