# Generated by Django 5.2.2 on 2025-09-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_register_addedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_register',
            name='Ast_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
