# Generated by Django 5.2.2 on 2025-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_register_ast_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_register',
            name='Ast_Brand',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='asset_register',
            name='Ast_Model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='asset_register',
            name='Ast_Type',
            field=models.CharField(max_length=30),
        ),
    ]
