# Generated by Django 5.2.2 on 2025-09-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_register_ast_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_listing',
            name='brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_listing',
            name='model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listing',
            name='Ast_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='assets.asset_register'),
        ),
    ]
