# Generated by Django 5.2.2 on 2025-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_vehicle_listing_brand_vehicle_listing_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_listing',
            name='Back_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle_listing',
            name='Front_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='maintaince',
            name='Document',
            field=models.FileField(blank=True, null=True, upload_to='maintaince/'),
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
