# Generated by Django 5.2.2 on 2025-09-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_vehicle_listing_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_listing',
            name='Plate_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
