# Generated by Django 5.2.2 on 2025-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('userid', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
