# Generated by Django 5.2.2 on 2025-09-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_log',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users_log',
            name='userid',
        ),
        migrations.AddField(
            model_name='users_log',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users_log',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users_log',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
