# Generated by Django 5.2.2 on 2025-09-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_users_log_email_remove_users_log_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_log',
            old_name='name',
            new_name='userid',
        ),
    ]
