# Generated by Django 5.2.2 on 2025-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('userid', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=20)),
                ('T_street', models.CharField(max_length=50)),
                ('T_District', models.CharField(max_length=30)),
                ('T_pincode', models.CharField(max_length=6)),
                ('P_street', models.CharField(max_length=50)),
                ('p_District', models.CharField(max_length=30)),
                ('p_pincode', models.CharField(max_length=6)),
                ('Account_number', models.CharField(max_length=30)),
                ('Bank_name', models.CharField(max_length=100)),
                ('Ifsc', models.CharField(max_length=12)),
                ('Position', models.CharField(max_length=4)),
                ('permission', models.CharField(max_length=8)),
            ],
        ),
    ]
