# Generated by Django 5.2.2 on 2025-09-13 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Docno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Docdate', models.DateTimeField()),
                ('Vehicle', models.CharField(max_length=10)),
                ('Booking_Status', models.CharField(max_length=10)),
                ('Meter_out', models.IntegerField()),
                ('Meter_in', models.IntegerField(blank=True, null=True)),
                ('Rent', models.IntegerField()),
                ('Allowed_km', models.IntegerField()),
                ('Add_km', models.IntegerField()),
                ('Latehour', models.DateTimeField()),
                ('Total_Days', models.IntegerField()),
                ('Discount_type', models.CharField(max_length=8)),
                ('Discount_value', models.IntegerField()),
                ('Tax_type', models.CharField(max_length=10)),
                ('Tax', models.IntegerField()),
                ('others_Type', models.CharField(max_length=20)),
                ('others_price', models.IntegerField()),
                ('Reciept', models.IntegerField()),
                ('Customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contracts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invno', models.CharField(max_length=10)),
                ('Docdate', models.DateTimeField(auto_now_add=True)),
                ('totalrent', models.IntegerField()),
                ('totalothers', models.IntegerField()),
                ('addkm', models.IntegerField()),
                ('latehour', models.IntegerField()),
                ('totaltax', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('method', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('bookno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contracts.booking')),
            ],
        ),
    ]
