# Generated by Django 5.2.2 on 2025-09-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timein',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
