# Generated by Django 5.2.2 on 2025-09-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0002_booking_timein'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='Payment_docno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='Total_exclude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='Total_include',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timein',
            field=models.DateField(blank=True, null=True),
        ),
    ]
