# Generated by Django 5.2.2 on 2025-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0003_booking_deposit_booking_payment_docno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Balance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
