# Generated by Django 5.2.2 on 2025-09-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0004_booking_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Docdate',
            field=models.DateField(),
        ),
    ]
