# Generated by Django 5.2.2 on 2025-09-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0005_alter_booking_docdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Latehour',
            field=models.IntegerField(),
        ),
    ]
