# Generated by Django 5.2.2 on 2025-09-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0006_alter_booking_latehour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Payment_docno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Total_exclude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Total_include',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.IntegerField(default=0),
        ),
    ]
