# Generated by Django 5.2.2 on 2025-09-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0007_alter_booking_balance_alter_booking_payment_docno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
