# Generated by Django 5.2.2 on 2025-09-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0008_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Vehicle',
            field=models.CharField(max_length=50),
        ),
    ]
