# Generated by Django 5.2.2 on 2025-09-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0009_alter_booking_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Vehicle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
